name: Notificar issues creado

on:
  issues:
    types: [opened, edited
    ,deleted
    ,transferred
    ,pinned
    ,unpinned
    ,closed
    ,reopened
    ,assigned
    ,unassigned
    ,labeled
    ,unlabeled
    ,locked
    ,unlocked
    ,milestoned
    ,demilestoned]

jobs:
  notify:
    runs-on: ubuntu-latest
    environment: test
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Enable Debug
        run: echo "ACTIONS_RUNNER_DEBUG=true" >> $GITHUB_ENV

      - name: Telegram Notify
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            游닉 **Notificaci칩n de Issue**

            **Usuario:** ${{ github.actor }}
            **Acci칩n:** ${{ github.event.action }}
            **T칤tulo del Issue:** ${{ github.event.issue.title }}
            **Estado del Issue:** ${{ github.event.issue.state }}
            **Descripci칩n del Issue:** ${{ github.event.issue.body }}
            **Etiquetas del Issue:** ${{ github.event.issue.labels  }}
            **URL del Issue:** ${{ github.event.issue.html_url }}
            **Repositorio:** ${{ github.repository }}