name: Notificar issues creado

on:
  issues:
    types: [opened, edited
    ,deleted
    ,transferred
    ,pinned
    ,unpinned
    ,closed
    ,reopened
    ,assigned
    ,unassigned
    ,labeled
    ,unlabeled
    ,locked
    ,unlocked
    ,milestoned
    ,demilestoned]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Telegram Notify
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: 5875976089
          token: 7069195716:AAGoFINKNewAa95miJsxiBCtVHy2Kb_H7-k
          message: |
          游닉 **Notificaci칩n de Issue**

          **Usuario:** ${{ github.actor }}
          **Acci칩n:** ${{ github.event.action }}
          **T칤tulo del Issue:** ${{ github.event.issue.title }}
          **Estado del Issue:** ${{ github.event.issue.state }}
          **Descripci칩n del Issue:** ${{ github.event.issue.body }}
          **Etiquetas del Issue:** ${{ github.event.issue.labels | map('name') | join(', ') }}
          **URL del Issue:** [${{ github.event.issue.html_url }}](${{ github.event.issue.html_url }})
          **Repositorio:** ${{ github.repository }}