name: Procesar Comentario en Issue

on:
  issue_comment:
    types: [created, edited, deleted]

jobs:
  process-comment:
    runs-on: ubuntu-latest
    environment: test
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Telegram Notify
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            📢 **Nuevo Comentario en Issue**

            **Usuario:** ${{ github.event.comment.user.login }}
            **Acción:** ${{ github.event.action }}
            **Comentario:** ${{ github.event.comment.body }}
            **Issue:** ${{ github.event.issue.title }}
            **Repositorio:** ${{ github.repository }}
            **URL del Issue:** ${{ github.event.issue.html_url }}
