name: Notificar pull request

on:
  pull_request:
    types: [opened, reopened]
    paths:
      - "**.js"

jobs:
  process-pull-request:
    runs-on: ubuntu-latest
    environment: test
    steps:
        
      - name: Enviar notificación a Telegram
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚀 **Nuevo Pull Request abierto**

            **Usuario:** ${{ github.event.pull_request.user.login }}
            **Título:** ${{ github.event.pull_request.title }}
            **Descripción:** ${{ github.event.pull_request.body }}
            **URL del Pull Request:** [${{ github.event.pull_request.html_url }}](${{ github.event.pull_request.html_url }})
            **Repositorio:** ${{ github.repository }}
