name: 'Test Trigger'
on:
  push:
    branches: ["main"]
    patchs: ["**.js"]

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:

      - name: Actualizar o installar npm
        run: npm install -g npm@latest

      - name: Checkout código
        uses: actions/checkout@v4
          #persist-credentials: true

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Versión de Node.js que deseas usar
          cache-dependency-path: .npmrc
      
      ##- name: Iniciar dependencias
      ##  run: npm init

      ##- name: Instalar dependencias
      ##  run: npm install

      - name: Ejecutar script Node.js
        run: node index.js  # Reemplaza 'index.js' con el nombre de tu script principal

      ##- name: slack-send
        ##uses: slackapi/slack-github-action@v1.26.0
            