name: 'Test Trigger'
on:
  push:
    branches: ["main"]
    patchs: ["**.js"]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      # Versión de Node.js que deseas usar
      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'  # Versión de Node.js que deseas usar

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar script Node.js
        run: node index.js  # Reemplaza 'tu_script.js' con el nombre de tu script

