name: 'Test Trigger'
on:
  push:
    branches:
      - main
    paths:
      - '**.js'

runs:
  using: 'node20'  # Especifica la versión de Node.js que tu acción requiere
  main: 'main.js'  # Ruta al archivo principal de tu acción

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Configurar Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Versión de Node.js que deseas usar

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar script Node.js
        run: node index.js  # Reemplaza 'index.js' con el nombre de tu script principal

